image: monachus/hugo

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  - hugo
  except:
  - master  

pages:
  script:
  - hugo --environment production
  artifacts:
    paths:
    - public
  only:
  - master    